language: generic
sudo: required
services:
    - docker

before_install:
        - docker build -t seedbg/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true seedbg/docker-react npm run test